added openMP support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -584,6 +584,8 @@ PACKAGE_URL=
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
 CXXFLAGS
+HAVE_OPENMP
+OPENMP_CFLAGS
 FFTW_LIBS
 FFTW_CFLAGS
 PKG_CONFIG_LIBDIR
@@ -640,6 +642,7 @@ ac_subst_files=''
 ac_user_opts='
 enable_option_checking
 with_x
+enable_openmp
 '
       ac_precious_vars='build_alias
 host_alias
@@ -1263,6 +1266,12 @@ if test -n "$ac_init_help"; then
 
   cat <<\_ACEOF
 
+Optional Features:
+  --disable-option-checking  ignore unrecognized --enable/--with options
+  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
+  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --disable-openmp        do not use OpenMP
+
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
@@ -1838,6 +1847,16 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
+
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+
+RBIN="${R_HOME}/bin/R"
+
+## OS checking borrowed from rgl package by Duncan Murdoch
 ##AC_CONFIG_AUX_DIR(src/build/autoconf)
 if test `uname` = "Darwin" ; then
   darwin="yes"
@@ -2996,7 +3015,7 @@ fi
 
 
 
-
+# from mwaved package by jrwishart
 # Check if the FFTW Library exists on the system
 { $as_echo "$as_me:${as_lineno-$LINENO}: Checking if FFTW3 library is available using pkg-config" >&5
 $as_echo "$as_me: Checking if FFTW3 library is available using pkg-config" >&6;}
@@ -3198,11 +3217,119 @@ if test "$HAVE_FFTW" == TRUE
 then
 	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: FFTW3 found!" >&5
 $as_echo "FFTW3 found!" >&6; }
-																		else
+else
   # Return message that package requires FFTW3 library
   { $as_echo "$as_me:${as_lineno-$LINENO}: result: FFTW library not found, please install fftw3" >&5
 $as_echo "FFTW library not found, please install fftw3" >&6; }
 fi
+
+
+
+# Check for OpenMP (from randomForests package)
+
+  OPENMP_CFLAGS=
+  # Check whether --enable-openmp was given.
+if test "${enable_openmp+set}" = set; then :
+  enableval=$enable_openmp;
+fi
+
+  if test "$enable_openmp" != no; then
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking for $CC option to support OpenMP" >&5
+$as_echo_n "checking for $CC option to support OpenMP... " >&6; }
+if ${ac_cv_prog_c_openmp+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+#ifndef _OPENMP
+ choke me
+#endif
+#include <omp.h>
+int main () { return omp_get_num_threads (); }
+
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_prog_c_openmp='none needed'
+else
+  ac_cv_prog_c_openmp='unsupported'
+	  	  	  	  	  	  	                                	  	  	  	  	  	  for ac_option in -fopenmp -xopenmp -openmp -mp -omp -qsmp=omp -homp \
+                           -Popenmp --openmp; do
+	    ac_save_CFLAGS=$CFLAGS
+	    CFLAGS="$CFLAGS $ac_option"
+	    cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+#ifndef _OPENMP
+ choke me
+#endif
+#include <omp.h>
+int main () { return omp_get_num_threads (); }
+
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_prog_c_openmp=$ac_option
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+	    CFLAGS=$ac_save_CFLAGS
+	    if test "$ac_cv_prog_c_openmp" != unsupported; then
+	      break
+	    fi
+	  done
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_prog_c_openmp" >&5
+$as_echo "$ac_cv_prog_c_openmp" >&6; }
+    case $ac_cv_prog_c_openmp in #(
+      "none needed" | unsupported)
+	;; #(
+      *)
+	OPENMP_CFLAGS=$ac_cv_prog_c_openmp ;;
+    esac
+  fi
+
+
+
+RBIN="${R_HOME}/bin/R"
+
+# Since some systems have broken OMP libraries we also check that the
+# actual package will work.
+ac_pkg_openmp=no
+if test -n "${OPENMP_CFLAGS}"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether OpenMP will work in a package" >&5
+$as_echo_n "checking whether OpenMP will work in a package... " >&6; }
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+#include <omp.h>
+int
+main ()
+{
+ return omp_get_num_threads ();
+  ;
+  return 0;
+}
+_ACEOF
+  "$RBIN" CMD SHLIB conftest.c 1>&5 2>&5 && "$RBIN" --vanilla -q -e "dyn.load(paste('conftest',.Platform\$dynlib.ext,sep=''))" 1>&5 2>&5 && ac_pkg_openmp=yes
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: ${ac_pkg_openmp}" >&5
+$as_echo "${ac_pkg_openmp}" >&6; }
+fi
+
+# If ${ac_pkg_openmp} = "yes" then we have OMP, otherwise it will be "no".
+if test "${ac_pkg_openmp}" = no; then
+  OPENMP_CFLAGS=''
+  HAVE_OPENMP=''
+  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: OpenMP does NOT appear to be supported on this system." >&5
+$as_echo "$as_me: WARNING: OpenMP does NOT appear to be supported on this system." >&2;}
+else
+  HAVE_OPENMP='-Dcimg_use_openmp'
+fi
+
+
+
+
 
 # Now substitute these variables in src/Makevars.in to create src/Makevars
 
